backend:
  name: github                              # Wajib "github", bukan "git-gateway"
  repo: abedeck/bebekbakar
  branch: main
  base_url: https://decap-oauth.abednega.workers.dev # Wajib pakai https://
  auth_endpoint: auth

media_folder: "content/posts/{{slug}}"
public_folder: ""

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Cover Image", name: "image", widget: "image", required: false, default: "cover.jpg" }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }